;
; PixelTransforms.ahk - generated by Patch-RemoveMCode.ahk. Do not edit by hand.
;
; ============================================================================
; Plain-AutoHotkey replacements for the machine-code blobs the upstream library
; uses. Transcribed from the C source in its own comments, and verified to
; produce byte-identical output - see Verify-MCodeRemoval.ahk.
;
; Buffer layout: 32-bit ARGB pixels, stride bytes per row.
; ============================================================================

OCR_GrayScale(ptr, w, h, stride) {
    offset := stride // 4, yEnd := h * offset, y := 0
    while (y < yEnd) {
        base := ptr + y * 4, x := 0
        while (x < w) {
            p := base + x * 4, argb := NumGet(p, 0, 'UInt')
            a := argb & 0xFF000000
            r := (argb & 0x00FF0000) >> 16, g := (argb & 0x0000FF00) >> 8, b := argb & 0xFF
            gray := (300 * r + 590 * g + 110 * b) >> 10
            NumPut('UInt', (gray << 16) | (gray << 8) | gray | a, p, 0)
            x++
        }
        y += offset
    }
    return 0
}

OCR_InvertColors(ptr, w, h, stride) {
    offset := stride // 4, yEnd := h * offset, y := 0
    while (y < yEnd) {
        base := ptr + y * 4, x := 0
        while (x < w) {
            p := base + x * 4, argb := NumGet(p, 0, 'UInt')
            a := argb & 0xFF000000
            r := (argb & 0x00FF0000) >> 16, g := (argb & 0x0000FF00) >> 8, b := argb & 0xFF
            NumPut('UInt', ((255 - r) << 16) | ((255 - g) << 8) | (255 - b) | a, p, 0)
            x++
        }
        y += offset
    }
    return 0
}

OCR_Monochrome(ptr, w, h, stride, threshold) {
    offset := stride // 4, yEnd := h * offset, y := 0
    while (y < yEnd) {
        base := ptr + y * 4, x := 0
        while (x < w) {
            p := base + x * 4, argb := NumGet(p, 0, 'UInt')
            r := (argb & 0x00FF0000) >> 16, g := (argb & 0x0000FF00) >> 8, b := argb & 0xFF
            lum := (77 * r + 150 * g + 29 * b) >> 8
            NumPut('UInt', (lum > threshold) ? 0xFFFFFFFF : 0xFF000000, p, 0)
            x++
        }
        y += offset
    }
    return 0
}